modLoader="javafml"
loaderVersion="[35,)"
license="${license}"
issueTrackerURL="${issue_tracker}"
[[mods]]
	modId="flightcore"
	version="${version}"
	displayName="${display}"
	updateJSONURL="${update_json}"
	displayURL="${page}"
	logoFile="${logo_file}"
	credits="${credits}"
	authors="${authors}"
	description='''${description}'''
[[dependencies.flightcore]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.flightcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
