modLoader="javafml"
loaderVersion="[37,)"
license="${license}"
issueTrackerURL="${issue_tracker}"
[[mods]]
    modId="flightcore"
    version="${version}"
    displayName="${display}"
    updateJSONURL="${update_json}"
    displayURL="${page}"
    logoFile="${logo_file}"
    credits="${credits}"
    authors="${authors}"
    description='''${description}'''
[[dependencies.flightcore]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.flightcore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
